### PR TITLE
Adding some missing attributes to Order and ChangeInNAV

### PR DESCRIPTION
**Pull request by troyev**
Hello,

Thanks for your work on this project! The client worked for me to download a flex report.

However, I had a few issues parsing the report. I got exceptions because of some missing attributes in Order and ChangeInNAV.

There was also an issue with openCloseIndicator="-" so I added UNKNOWN to the openCloseIndicator enum for the dash.

 so this pull request adds the missing fields. It also includes the relevant tests.

-Troy

### CODE REVIEW

**Comment by csingley** [comment]
Thanks, looks great.  It's hard keeping on top of IB's changes to the Flex format; they're like squirrels with ADHD and an allergy to writing documentation.

One thing I don't understand though.  Have they dropped using `<Trade>` inside of `<Trades>`, then?  And now they're using `<Order>` for both `<Trades>` and `<TradeConfirms>` ?

**Comment by troyev** [comment]
I think both `<Trade>` and `<Order>` are valid inside of `<Trades>`

When you edit a flex report, and click Trades, you will see 6 check boxes at the top: Symbol Summary, Asset Class, Orders, Executions, Closed Lots, and Wash Sales.

When you select Orders you will get `<Order>` inside of `<Trades>` and when you select Executions you will get `<Trade>` inside of `<Trades>`

I believe the main difference is that Executions will give you an entry for each partial fill of a trade. Trades will just give you one entry for the whole order.

**Comment by titov-vv** [comment]
Yes, IB added "Options" for some of sections. This is how it looks for Trades now:
IBRK account   
And more important: if you select "Symbol Summary" and "Executions" you will have more `<Trades>` - there will be "old" ones with `levelOfDetail="EXECUTION"` and "totals" with `levelOfDetail="SUMMARY"`

**Comment by csingley** [comment]
Thanks gentlemen.

> When you select Orders you will get <Order> inside of <Trades> and when you select Executions you will get <Trade> inside of <Trades>

> I believe the main difference is that Executions will give you an entry for each partial fill of a trade. Trades will just give you one entry for the whole order

Ah, got it.

> And more important: if you select "Symbol Summary" and "Executions" you will have more <Trades> - there will be "old" ones with levelOfDetail="EXECUTION" and "totals" with levelOfDetail="SUMMARY"

And if you select both "Symbol Summary" and "Orders", you'd presumably get the same behavior for `levelOfDetail` within `<Trades><Order>` ?

But anyway, this is really a concern for application code, not the humble `ibflex` library...  we merely report...

**Comment by titov-vv** [comment]
Can't say for sure as I didn't dig deeper in it. 
But yes, you are right that it's an job for application to distinguish records based on `levelOfDetail` field and use right information.

**Pull request merged**
