### PR TITLE
[Add] new type: endingCashIBUKL

### PR DESCRIPTION
**Pull request by ileodo**

### CODE REVIEW

**Comment by ileodo** [comment]
bouncing this up..

**Comment by csingley** [comment]
Sorry for the delay

```
endingCashIBUKL: Optional[Decimal]
```
That's breaking CI - I just imported the `decimal` module into `Types` namespace; you'll need to declare `Optional[decimal.Decimal]`.

**Comment by csingley** [comment]
Hey thanks for the PR - but check it out, we already got this in [4f4e2b7](https://github.com/csingley/ibflex/commit/4f4e2b7604f58c46028d8a067fc66ae53b9ebb36)

**Comment by ileodo** [comment]
thanks! didn't notice that due to the version in pypi is still 0.15.

**Pull request closed without merging**
