### PR TITLE
Added `Code` enum for fractional shares execution types

### PR DESCRIPTION
**Pull request by pavitrakumar78**
"P;RP" and "FP;P" were codes that are new to me and to the library. It seems these are related to fractional executions. See examples below.

```
<Trade accountId="XXXXXXXX" acctAlias="" model="" currency="USD" fxRateToBase="1" assetCategory="STK" symbol="LMNR" description="LIMONEIRA CO" conid="48916802" securityID="US5327461043" securityIDType="ISIN" cusip="532746104" isin="US5327461043" listingExchange="NASDAQ" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="3608519881" putCall="" reportDate="20210312" principalAdjustFactor="" dateTime="20210312,133036" tradeDate="20210312" settleDateTarget="20210316" transactionType="ExchTrade" exchange="IBKRATS" quantity="0.0023" tradePrice="18.74" tradeMoney="0.043102" proceeds="-0.043102" taxes="0" ibCommission="-0.01" ibCommissionCurrency="USD" netCash="-0.053102" closePrice="19.01" openCloseIndicator="O" notes="FP;P" cost="0.053102" fifoPnlRealized="0" fxPnl="0" mtmPnl="0.0006" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="15738560208" buySell="BUY" ibOrderID="1807825132" ibExecID="000102df.604bd424.01.01" brokerageOrderID="0030c27b.0000ebaf.604b5ebf.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="0030c27b.00018cda.606138d0.0001" orderTime="20210312,133036" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="" isAPIOrder="N" accruedInt="0" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

<Trade accountId="XXXXXXXX" acctAlias="" model="" currency="USD" fxRateToBase="1" assetCategory="STK" symbol="LMNR" description="LIMONEIRA CO" conid="48916802" securityID="US5327461043" securityIDType="ISIN" cusip="532746104" isin="US5327461043" listingExchange="NASDAQ" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="3608519907" putCall="" reportDate="20210312" principalAdjustFactor="" dateTime="20210312,133036" tradeDate="20210312" settleDateTarget="20210316" transactionType="ExchTrade" exchange="IBKRATS" quantity="26" tradePrice="18.72" tradeMoney="486.72" proceeds="-486.72" taxes="0" ibCommission="-0.99" ibCommissionCurrency="USD" netCash="-487.71" closePrice="19.01" openCloseIndicator="O" notes="P" cost="487.71" fifoPnlRealized="0" fxPnl="0" mtmPnl="7.54" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="15738560215" buySell="BUY" ibOrderID="1807825132" ibExecID="0001a2f4.604bc209.01.01" brokerageOrderID="0030c27b.0000ebaf.604b5ebf.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="377836300B" orderTime="20210312,133036" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="" isAPIOrder="N" accruedInt="0" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />

<Trade accountId="XXXXXXXX" acctAlias="" model="" currency="USD" fxRateToBase="1" assetCategory="STK" symbol="LMNR" description="LIMONEIRA CO" conid="48916802" securityID="US5327461043" securityIDType="ISIN" cusip="532746104" isin="US5327461043" listingExchange="NASDAQ" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="3608519930" putCall="" reportDate="20210312" principalAdjustFactor="" dateTime="20210312,133036" tradeDate="20210312" settleDateTarget="20210316" transactionType="ExchTrade" exchange="IBKRATS" quantity="0.7086" tradePrice="18.68" tradeMoney="13.236648" proceeds="-13.236648" taxes="0" ibCommission="0" ibCommissionCurrency="USD" netCash="-13.236648" closePrice="19.01" openCloseIndicator="O" notes="P;RP" cost="13.236648" fifoPnlRealized="0" fxPnl="0" mtmPnl="0.2338" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="15738560225" buySell="BUY" ibOrderID="1807825132" ibExecID="000102df.604bd422.01.01" brokerageOrderID="0030c27b.0000ebaf.604b5ebf.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="0030c27b.00018cda.606138cf.0001" orderTime="20210312,133036" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="" isAPIOrder="N" accruedInt="0" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 ()" />
```

I'm not 100% sure if they mean the definitions I've added, but please change it as you see fit.

### CODE REVIEW

**Comment by csingley** [comment]
I'm glad you're improving the library!

The parser is trying to convert your data to an instance of the class `ibflex.Types.Trade`, whose class definition reads (in relevant part):

```
    notes: Tuple[enums.Code, ...] = ()  # separator = ";"
```

The type annotation is telling you that the class attribute `Trade.notes` represents a tuple (i.e. a sequence), containing multiple instances of type `enums.Code`.  If you look at the end of the line there, you'll find that I have helpfully appended to the code a little comment, indicating that the items within the tuple are delimited by a ";" character.

Data like "P;RP" or "FP;P" represents Interactive Brokers attaching multiple notes to a single Trade.  You'll notice that `ibflex.enums.Code.PARTIAL` is already defined for code "P".  You have two new codes: "RP" and "FP".

**Comment by pavitrakumar78** [comment]
I'm not able to generate the PDF on the flex queries tab to get the exact meanings for it, so I'll update the pull for now and later on update the definition with what I get in the PDF from IB.

**Comment by csingley** [comment]
> I'm not able to generate the PDF on the flex queries tab to get the exact meanings for it

It's not in the Flex queries tab; it's in the other tab where you generate human-readable account statements... doesn't have to be PDF; they also offer HTML and other formats.  They sometimes print these off and mail hard copies to you.  The Notes section is down at the bottom of the account statement.

If possible, do me a favor and double-check this before we commit this patch (which looks totally fine to me).  I try to take pains to follow Interactive Brokers definitions as accurately as possible.  If they're telling us what these codes are supposed to mean, I'd like to stick close to that.

**Comment by pavitrakumar78** [comment]
> > I'm not able to generate the PDF on the flex queries tab to get the exact meanings for it
> 
> It's not in the Flex queries tab; it's in the other tab where you generate human-readable account statements... doesn't have to be PDF; they also offer HTML and other formats. They sometimes print these off and mail hard copies to you. The Notes section is down at the bottom of the account statement.
> 
> If possible, do me a favor and double-check this before we commit this patch (which looks totally fine to me). I try to take pains to follow Interactive Brokers definitions as accurately as possible. If they're telling us what these codes are supposed to mean, I'd like to stick close to that.

Sure!
Here's the copy:
image

RP: IB acted as riskless principal for the fractional share portion of this trade
FP: IB acted as principal for the fractional share portion of this trade

**Comment by csingley** [comment]
There you go, that's it.  Would you mind updating the names for the enum values to reflect that understanding?  Maybe something like `FRACPRINCIPAL` and `FRACRISKLESSPRINCIPAL`... and the notes make it look like `RPA` is another, even longer enum name waiting to happen... what would that be, `FRACRISKLESSPRINCIPALWHOLEAGENT` ??  A bunch of Series 7 details that hold no interest for me!

**Review by pavitrakumar78 — COMMENTED** [review]
Note: also had to shift the explanation comment alignment because the new code's length is longer than the rest.

**Comment by pavitrakumar78** [comment]
> There you go, that's it. Would you mind updating the names for the enum values to reflect that understanding? Maybe something like `FRACPRINCIPAL` and `FRACRISKLESSPRINCIPAL`... and the notes make it look like `RPA` is another, even longer enum name waiting to happen... what would that be, `FRACRISKLESSPRINCIPALWHOLEAGENT` ?? A bunch of Series 7 details that hold no interest for me!

Done! Can you please check?

**Comment by csingley** [comment]
That's fine.  Thank you.  If you could just update your other PR to fix the type for `Trade.fineness`, I think we'd be all done here for now.

**Comment by pavitrakumar78** [comment]
> That's fine. Thank you. If you could just update your other PR to fix the type for `Trade.fineness`, I think we'd be all done here for now.

Done! https://github.com/csingley/ibflex/pull/33/commits/2213e3491bc67bb09acea7852297b629919a21df

**Pull request merged**
