### PR TITLE
extend Trade and SecurityInfo types with new fields

### PR DESCRIPTION
**Pull request by grunichev**
Added 2 new fields that are presented in flex report by default.

### CODE REVIEW

**Comment by titov-vv** [comment]
Alexey, 
from my experience - Christopher usually ask to add test cases for new fields in the same way as already done for any other.
So, I would propose you not to wait his feedback but add test cases for these 2 fields (I may assist if required)

**Comment by csingley** [comment]
Yeah the new fields are fine.  I'd just like to have a test case incorporating real data (sanitized of any sensitive information).  This is important for long-term maintainability of the library code.

Thanks!

**Comment by grunichev** [comment]
@csingley @titov-vv thanks guys, totally make sense. I'd ask before adding tests if somebody can check real values for these files before, because in my reports the are both emtpy (settlementPolicyMethod="" and accruedInt="").
I assume accruedInt is safe, because it exists in other Types, but I don't have any idea what settlementPolicyMethod would be.

**Comment by csingley** [comment]
Well, if we simply don't have data, then it will be difficult to write good tests.  Unfortunately I don't have any myself.  Vlad I don't suppose you have anything non-NULL for these fields anywhere?

`Trade.accruedInt` should have decimal values for bond trades.

I guess `SecurityInfo.settlementPolicyInfo` should be something like T+2, T+3, etc.  Maybe?

If we can't get any data, I'll just merge the patch anyway.  The library will be improved by having these, even without proper tests.  It would just be better to have the tests, to ensure that any later changes to the parser don't break data that is currently parsed correctly.

**Comment by titov-vv** [comment]
I've checked my recent reports - there are no such fields. I expected to find settlementPolicyInfo in <SecuritiesInfo> but it isn't there... I may assume it is because my flex report was created some time ago and it haven't been updated with recently added fields. 
Thus, nothing tangible from my side. But I'll try to create new report in spare time and notify you if I'll have something interesting there.

**Comment by csingley** [comment]
In the meantime, might as well merge this improvement!

**Pull request merged**
